################################### Default Configuration ############################
baseurl = "http://www.ayanev.eu/aqua-links/"
# languageCode = "en"
title = "AquaLinks"
theme = "vex-blog"

#################################### Plugins ##########################################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://fonts.googleapis.com/css?family=Droid+Serif:400i|Source+Sans+Pro:300,400,600,700"
  [[params.plugins.css]]
  URL = "https://fonts.googleapis.com/css?family=Josefin+Sans:300,400,600,700"
  [[params.plugins.css]]
  URL = "css/bootstrap.min.css"
  # TODO [ay]: remove
  # [[params.plugins.css]]
  # URL = "css/theme-fonts.css"
  [[params.plugins.css]]
  URL = "css/owl.carousel.css"
  [[params.plugins.css]]
  URL = "css/magnific-popup.css"
  [[params.plugins.css]]
  URL = "https://cdn.snipcart.com/themes/v3.0.3/default/snipcart.css"
  [[params.plugins.css]]
  URL = "css/font-awsome-allcss-v51.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/jquery-2.1.1.min.js"
  [[params.plugins.js]]
  URL = "js/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "js/owl.carousel.min.js"
  [[params.plugins.js]]
  URL = "js/jquery.magnific-popup.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.snipcart.com/themes/v3.0.3/default/snipcart.js"
  [[params.plugins.js]]
  URL = "https://kit.fontawesome.com/a23f4a760d.js"


###################################### Navigation ######################################
[menu]

  # TODO [ay]: remove unnecessary lines of code  
  [[menu.main]]
  name = "Features"
  URL = "feature"
  weight = 2
  
  # [[menu.main]]
  # name = "Gallery"
  # URL = "gallery"
  # weight = 3
  
  [[menu.main]]
  name = "Testimonial"
  URL = "testimonial"
  weight = 4

  [[menu.main]]
  name = "Team"
  URL = "team"
  weight = 5

  # [[menu.view]]
  # name = "Blog"
  # URL = "blog"
  # weight = 6

  [[menu.view]]
  name = "FAQ"
  URL = "faq"
  weight = 7

  # [[menu.view]]
  # name = "Contacts"
  # URL = "contacts"
  # weight = 8


########################### Default parameters ##########################
[params]
logo = ""
home = "Home"
# Meta data
description = "Aqua control systems"
author = "AquaLinks"
# Google Analitycs
google_analitycs_id = "UA-135269393-2"
# snipcart public api key
# snipcart_api = "ZDgxY2ZiM2EtMWRmMi00M2ZkLWI1MDAtNzA2MDc0Y2Q1MzJlNjM3MTAzNDIwOTQ1NDA4NjM4"
snipcart_api = "MjgyZmNiMDAtNDBjMy00N2RlLTlmYTEtNzc3MGIwZmI4ZDFhNjM3MTY4NjY1OTk1NjIzODcz"
# copyright
copyright = "Copyright 2019 &copy; AquaLinks | All right reserved."

# Preloader
[params.preloader]
enable = false
preloader = "" # use .png , .svg or .gif format

[social]
twitter = "#"
github = "#"
instagram = "#"
linkedin = "#"
dribbble = "#"
youtube = "#"
facebook = "https://fb.me/AquaLinksMedia"
mme = "https://m.me/AquaLinksMedia"
